name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: install
      run: npm install
    - name: run unit tests
    - run: npm run test:unit
    - name: run e2e tests
    - run: npm run test:e2e
